#!/usr/bin/perl
# https://www.intermediateperl.com/downloads/5.References.And.Scoping/make_coconet_dat.pl
use strict;
use warnings;
use v5.10;

my $records = shift // 10;

my @networks = (
    [qw(example.org host1 host2 host3)],
    [qw(example.net hostA hostB)],
    [qw(example.com host)],
);

my @hosts = map {
    my ( $domain, @hosts ) = @$_;

    map { "$_.$domain" } @hosts;
} @networks;

for ( 1 .. $records ) {
    my ( $src, $dst ) = map { @hosts[ rand(@hosts) ] } 1 .. 2;
    redo if $src eq $dst;  # we don't use net to communicate to ourselves
    my $bytes = int rand 10_000;
    say join "\t", $src, $dst, $bytes;
}
