#!/usr/bin/perl -sw
use vars qw($h $f $o $w $p);

if ($h) {
        print <<EOF;
NAME

  splunk-search - create (part of) Splunk search command to be pasted into web search bar

SYNOPSIS

  splunk-search -o=OPERATOR [-w] [-f=FIELD] [FILE(S)]

    -w      append '*' to hostnames (wildcard mode)
    -p      put parenthesis around hostnames

EXAMPLES

  echo host1 host2 host3 | splunk-search -f=host -o=OR

  splunk-search -f=src -o=OR subnets_copied_from_excel.txt
EOF
        exit;
}

die "Missing -o switch. Use -h to get help.\n" if not defined $o;

$values = do { local $/; <> };
die "Missing input, exiting ...\n" unless $values;
@values = split ' ', $values;

for $value (@values) {
        unless ($value =~ /^[\d\.]+$/) { # only hostnames not IP addresses
            $value .= '*' if $w;
            $value = "($value)" if $p;
        }
        if ($f) {
                $expr = qq($f=$value);
        } else {
                $expr = qq($value);
        }
        push @expressions, $expr;
        $count++;
}

$sep = "\n" . "-" x 80 . "\n";
print "Processed $count values";
print $sep, '(', join(" $o ", @expressions), ')', $sep;
