#!/usr/bin/perl -sw
use vars qw($h $f $o);

if ($h) {
        print <<EOF;
Create (part of) Splunk search command to be pasted into web search bar.

  $0 -f=FIELD -o=OPERATOR

EXAMPLES

  echo host1 host2 host3 | $0 -f=host -o=OR
  $0 -f=src -o=OR subnets_copied_from_excel.txt
EOF
        exit;
}

$values = do { local $/; <> };
die "Missing input, exiting ...\n" unless $values;
@values = split ' ', $values;

for $value (@values) {
        $value .= '*' unless $value =~ /^[\d\.]+$/;
        $expr = qq($f=$value);
        push @expressions, $expr;
        $count++;
}

$sep = "\n" . "-" x 80 . "\n";
print "Processed $count values";
print $sep, '(', join(" $o ", @expressions), ')', $sep;

